events: do not unwrap send_unique()
Avoids panic when pressing 'q' early running streams_example.rs:

    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: sending on a closed channel',
    ...
    14: streampager::file::{{impl}}::new_streamed::{{closure}}<pipe::PipeReader>
      at .\src\file.rs:154

Now streams_example.rs no longer panic, but it still blocks on the
writer threads.